### ISSUE TITLE
API Functionality #6 out of 10 - abchomeowner.com 

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/abchomeowner.com#1]
@codextiny
Please add API functionality to this new site. Please add pop-up form to the following: 
new microsite: [https://abchomeowner.com/wp-admin/admin.php?page=siteground-dashboard.php](url)
Credentials:
U: [[support@homeowner.ai](mailto:support@homeowner.ai)]
PW: M!l3st0nesL@bs

1.[ Home Page:](https://abchomeowner.com/)

Update search bar with API functionality

Add pop up form to Get Started Button in header on home page 

2. [How it Works Page:](https://abchomeowner.com/how-it-works/)
Add pop up form to claim my home button in hero image and cta at bottom

**Comment by codextiny** [comment]
@shannonbaldwin 

Added popup functionality, please check

**Comment by shannonbaldwin** [comment]
@codextiny Please add pop-up in prefooter CTA on home page and how it works page.
![image](https://github.com/user-attachments/assets/18c3a8d6-9e19-4285-a728-98d19212a8df)

**Comment by codextiny** [comment]
@shannonbaldwin 

Added, please check

**Comment by shannonbaldwin** [comment]
@codextiny Can you please help me link this section to the "Home Services" page and tell me how you did it? 
![image](https://github.com/user-attachments/assets/f0092074-b3a4-4fe5-b6aa-6c8dd85ddc29)

Also, are there any other search bar design options for the home page?

**Comment by codextiny** [comment]
@shannonbaldwin 

![image](https://github.com/user-attachments/assets/26b3f309-05d1-413f-8032-def2649a7f2d)

please check attached .

**Comment by codextiny** [comment]
@shannonbaldwin 

There is no already made designs for search bar, you can give us design, we will make it same like your design .

**Comment by shannonbaldwin** [comment]
@codextiny 

Need updates to this page [https://abchomeowner.com/contact-us/](url)

1. decrease spacing here
![image](https://github.com/user-attachments/assets/887aa833-6495-4050-9a03-f7f656aa0793)

2. When someone sends a message, please update that email who will receive messages to **bojenkins@goanteater.com**. Please also show me where you update this in WP? 
![image](https://github.com/user-attachments/assets/45a389dc-6375-46a8-be77-074a2467fe19)

3. I'd like the title of this to be "ABC Home & Commercial Services" instead of the actual address "9475 US-290" both in the card to the left and near the marker in the center of the map

![image](https://github.com/user-attachments/assets/5abe2cac-d680-4e55-b022-65a438028437)

4. Can we change the color of the red marker in middle to the green accent color? Hex #36834B
![image](https://github.com/user-attachments/assets/08543b49-64fb-4fc1-8499-233ef39cc785)

**Comment by codextiny** [comment]
@shannonbaldwin 

first point done.

![image](https://github.com/user-attachments/assets/ec912d90-16ab-4151-a0bc-2d66a6170eb6)
2. you can change email from here, please see screenshot.

rest of two points we are checking..

**Comment by codextiny** [comment]
@shannonbaldwin 

both changes are not related to coding, these are related to google maps, you need to add your desired location name against your address then it will automatically show here or second marker color its not in our hand because its also from google maps side, we didnt add any code its default module .

Thanks

**Comment by shannonbaldwin** [comment]
@codextiny Can you please help with mobile view here on the home page?

<img width="501" alt="image" src="https://github.com/user-attachments/assets/3df5166c-8dbe-47c8-b0f0-bd8c5330e5c4">

**Comment by shannonbaldwin** [comment]
@codextiny The star rating on home page is not showing up on live website. Only preview. 

![image](https://github.com/user-attachments/assets/fc7d868e-0b9c-4cd2-9abd-683b11839aab)

**Comment by codextiny** [comment]
@shannonbaldwin 

fixed both issues, for star icons, we have changed the library because star icons not working on live with font awesome, now we have used uicore icons ..

and also adjusted the logo on mobile.

please check ..
