### ISSUE TITLE
https://abchomeowner.com/

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/abchomeowner.com#2]
@codextiny 

How can I get the video to play once you click the play icon?? I think this is a WP setting? I am trying to avoid hitting play a second time.

![image](https://github.com/user-attachments/assets/ee65c23f-f9ed-469d-8a25-4e8c857f22c1)

**Comment by codextiny** [comment]
@shannonbaldwin 
Can you please give us the admin login credentials?

**Comment by shannonbaldwin** [comment]
it is in this issue's repository.

Credentials:
U: [[support@homeowner.ai](mailto:support@homeowner.ai)]
PW: M!l3st0nesL@bs

**Comment by codextiny** [comment]
@shannonbaldwin 

We have checked the Theme and elementor options but it looks like all the options are setup correctly but still video is not playing. We can make the video play onclick of icon with custom JS codes.

Please confirm if you want us to proceed?

**Comment by shannonbaldwin** [comment]
@codextiny Yes, please.

**Comment by codextiny** [comment]
@shannonbaldwin 

It's done please check

**Comment by shannonbaldwin** [comment]
@codextiny It still shows a glimpse of the thumbnail.

**Comment by codextiny** [comment]
@shannonbaldwin 

its from vimeo's side, because its vimeo's iframe .

**Comment by shannonbaldwin** [comment]
@codextiny Do you have suggestions on how I can fix?

**Comment by shannonbaldwin** [comment]
@codextiny Can you please remove the code on both videos? I would prefer the original option so a flash of the thumbnail does not show. It looks like a mistake from the user experience.

**Comment by codextiny** [comment]
@shannonbaldwin 

removed the script, please check
